### 12.1 异常概述

#### 例12.1 在项目中创建类```Baulk```,在主方法中定义```int```型变量，将0作为除数赋值给该变量

```Baulk.java
import static java.lang.System.out;

public class Baulk {

	public static void main(String[] args) {
		// TODO 自动生成的方法存根
		int res=3/0;
		out.println(res);
	}

}

输出:
Exception in thread "main" java.lang.ArithmeticException: / by zero（异常位置）
	at Baulk.main(Baulk.java:7)


```

## 12.2 处理程序异常错误

### 12.2.1 错误

#### 例12.2 在项目中创建类```Thundering```,在主方法中实现将非字符型数值转换为```int```型，运行程序，系统会报出异常提示。

```Thundering.java
import static java.lang.System.out;

public class Thundering {

	public static void main(String[] args) {
		// TODO 自动生成的方法存根
		String str="lili";
		out.println(str+"年龄是:");
		int age=Integer.parseInt("20L");
		out.println(age);
	}

}


输出：
lili年龄是:Exception in thread "main" 
java.lang.NumberFormatException: For input string: "20L"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:658)
	at java.base/java.lang.Integer.parseInt(Integer.java:776)
	at Thundering.main(Thundering.java:9)


```

### 12.2.2 捕捉异常

#### 例12.3 在项目中创建类```Take```，在主方法中使用```try-catch```语句块将可能出现的异常语句进行异常处理。

```Take.java
import static java.lang.System.out;

public class Thundering {

	public static void main(String[] args) {
		// TODO 自动生成的方法存根
		try {
			String str="lili";
			out.println(str+"年龄是:");
			int age=Integer.parseInt("20L");
			out.println(age);
		}catch(Exception e) {
			e.printStackTrace();
		}
		out.println("program over");
	}

}


#### 输出：
lili年龄是:
java.lang.NumberFormatException: For input string: "20L"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:658)
	at java.base/java.lang.Integer.parseInt(Integer.java:776)
	at Thundering.main(Thundering.java:10)
program over


```

### 12.4 自定义异常

#### 例12.4 创建自定义异常，在项目中创建类```MyException```，该类继承```Exception```

```MyException.java
public class MyException extends Exception{
	public MyException(String ErrorMessage) {
		super(ErrorMessage);
	}
}

```

#### 例12.5 在项目中创建类```Tran```,该类中创建一个带有```int```型参数的方法```arg()```,
#### 该方法用来检查参数是否小于0或大于100，如果参数小于0或者大于100，则通过```throw```关键字抛出一个```MyException```异常对象，
#### 并在```main()```方法中捕捉该异常

```Tran.java
import static java.lang.System.out;


public class Tran {
	//定义方法，抛出异常
	static int arg(int number1,int number2) throws MyException{
		if(number1<0||number2<0) {							//判断方法中参数是否满足指定条件
			throw new MyException("不可以使用负数");			//错误信息
		}
		if(number1>100||number2>100) {
			throw new MyException("数值太大了");				//错误信息
		}
		
		return (number1+number2)/2;
	}
	
	
	public static void main(String[] args) {
		// TODO 自动生成的方法存根
		try {
			int res=arg(102,150);
			out.println(res);
		}catch(MyException e) {
			out.println(e);				//输出异常信息
		}
	}

}


```


## 12.5 在方法中抛出异常

### 12.5.1 使用```throws```关键字抛出异常

#### 例12.6 在项目中创建类```Shoot```，在该类中创建方法```pop()```，在该方法中抛出```NegativeArraySizeException```异常，在主方法中调用该方法，并实现异常处理

```Shoot.java

import static java.lang.System.out;

public class Shoot {

	static void pop() throws NegativeArraySizeException{
		//定义方法并抛出NegativeArraySizeException 异常
		int[] arr=new int[-3];						//创建数组
	}
	
	public static void main(String[] args) {			
		// TODO 自动生成的方法存根
		try {												//try语句处理异常信息
			pop();											//调用pop()方法
		}
		catch(NegativeArraySizeException e) {
			out.println("pop()方法中抛出的异常");			///输出异常信息
		}
	}

}

```

### 12.5.2 使用```throw```关键字抛出异常

#### 例12.8 使用```throw```关键字捕捉异常，在项目中创建```Captor```类，该类中的```quoient()```方法传递两个```int```型参数，
#### 如果其中的一个参数为负数，则会抛出```MyException```异常,最后在```main()```方法中捕捉异常

```

import static java.lang.System.out;

public class Captor {

	static int quotient(int x,int y) throws MyException{		//定义方法抛出异常
		if(y<0)
			throw new MyException("除数不能是负数");
		return x/y;
	}
	
	
	public static void main(String[] args) {
		// TODO 自动生成的方法存根
		
		try {
			int res=quotient(3, -1);
		}catch(MyException e) {						//处理自定义异常
			out.println(e.getMessage());			//输出异常信息
		}catch(ArithmeticException e) {				//处理ArithmeticException异常
			out.println("除数不能为0");				//输出提示信息
		}catch(Exception e) {						//处理其他异常
			out.println("程序发生了其他的异常");		//输出提示信息
		}
		
	}

}



```




